vich_uploader:
  db_driver: orm
  mappings:
    activite_images:
      uri_prefix: /images/upload/activite
      upload_destination: '%kernel.project_dir%/public/images/upload/activite'
    activite_photo_images:
      uri_prefix: /images/upload/activite/images
      upload_destination: '%kernel.project_dir%/public/images/upload/activite/images'